#spring.application.name=softweek
#spring.datasource.url=jdbc:postgresql://192.168.130.19:30000/facop
#spring.datasource.username=facopDev
#spring.datasource.password=N@pgdefaultFacop2024
#spring.datasource.driver-class-name=org.postgresql.Driver
#server.port=8081
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring.application.name=softweek

spring.datasource.url=jdbc:postgresql://postgres-service.facop.svc.cluster.local:5432/facop

spring.datasource.username=facopDev
spring.datasource.password=N@pgdefaultFacop2024
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

