--Insert de Subcategorias
INSERT INTO SUBCATEGORIA (ID_CATEGORIA, NOME, ATIVO, COR)
VALUES
    (1, 'CAMISAS DE ALGODÃO', TRUE, 'VERDE'),
    (1, 'CAMISAS POLO', TRUE, 'AMARELO'),
    (2, 'CALÇAS JEANS', TRUE, 'AZUL'),
    (2, 'CALÇAS DE MOLETOM', TRUE, 'CINZA'),
    (3, 'JAQUETAS DE INVERNO', TRUE, 'MARRON'),
    (3, 'JAQUETAS LEVES', TRUE, 'LARANJA'),
    (4, 'VESTIDOS LONGOS', TRUE, 'VIOLETA'),
    (4, 'VESTIDOS CURTOS', TRUE, 'ROSA'),
    (5, 'SAPATOS DE SALTO', TRUE, 'PRETO'),
    (5, 'SAPATOS CASUAL', TRUE, 'BRANCO');